name: EverythingPlugin
version: ${project.version}
main: com.bluemarien.everythingplugin.EverythingPlugin
api-version: 1.15
depend: [Vault]
authors: [Bluemarien]
description: This plugin adds various features and commands like heal, feed, and an xp bank
commands:
  heal:
    description: Heals the player to full health.
    usage: /heal [player]
  feed:
    description: Feeds the player to full hunger.
    usage: /feed [player]
  exp:
    description: Give other players experience levels.
    usage: /exp set <level> [player] | /exp give <level> <player1> [player2] | /exp clear [player]
  xpb:
    description: Stores the player's experience levels.
    usage: /xpb | /xpb <create|top10> | /xpb <deposit|withdrawal> <levels>