name: EverythingPlugin
version: ${project.version}
main: com.bluemarien.everythingplugin.EverythingPlugin
api-version: 1.16
depend: [Vault]
authors: [Bluemarien]
description: Adds misc. features like heal, feed, xp sharing, and an xp bank.
commands:
  heal:
    description: Heals the player to full health.
    usage: /heal [player]
  feed:
    description: Feeds the player to full hunger.
    usage: /feed [player]
  xpshare:
    description: Give other players xp levels.
    usage: /xpshare [help | ?] | /xpshare <levels> <player>
  xpbank:
    description: Stores the player's xp levels.
    usage: /xpbank [help | ?] | /xpbank top10 | /xpb <deposit | d | withdrawal | w> <levels>
  warp:
    description: Teleports players to warp locations.
    usage: /warp [help | ?] | /warp <warp name> | /warp <create | c> <warp name> | /warp <delete | d> <warp name>