name: EverythingPlugin
version: ${project.version}
main: com.bluemarien.everythingplugin.EverythingPlugin
api-version: 1.16
depend: [Vault]
authors: [Bluemarien]
description: Adds misc. features like heal, feed, xp sharing, xp banks, warping, gifting, and homes.
commands:
  heal:
    description: Heals the player to full health.
    usage: /heal [player]
  feed:
    description: Feeds the player to full hunger.
    usage: /feed [player]
  xpshare:
    description: Give other players xp levels.
    usage: /xpshare [help | ?] | /xpshare <levels> <player>
    aliases: [xps]
  xpbank:
    description: Stores the player's xp levels.
    usage: /xpbank [help | ?] | /xpbank top10 | /xpbank <deposit | d | withdrawal | w> <levels>
    aliases: [xpb]
  warp:
    description: Teleports players to warp locations.
    usage: /warp [help | ?] | /warp <list | l> | /warp <warp name> | /warp <create | c> <warp name> | /warp <delete | d> <warp name>
  gift:
    description: Gift items to other players.
    usage: /gift [help | ?] | /gift <player> [amount]
  home:
    description: Teleports the player home.
    usage: /home [home name]
  sethome:
    description: Sets a new home for the player.
    usage: /sethome [home name]
  delhome:
    description: Deletes a player's home.
    usage: /delhome <home name>
  listhomes:
    description: Lists all the player's homes.
    usage: /listhomes